name: only_transfer
description: "Sistema VIP OnlyTransfer"
publish_to: 'none'

version: 1.0.1+14

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.2.5
  share_plus: ^7.1.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8
  geocoding: ^4.0.0
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  flutter_stripe: ^12.4.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^1.2.1
  shared_preferences: ^2.2.2
  http: ^0.13.6
 # google_places_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_typeahead: ^5.2.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_app.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_app.png
    - assets/imatges/logo_onlyt.png
    - assets/fons_app.jpg
    - assets/imatges/onlytransfer_logo.png
    - assets/lang/
