// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABhzG_yvIzP9y7XaHg3sH1CkTA3JUaXhU',
    appId: '1:231873137659:web:fc5d643b30979fc13d195e',
    messagingSenderId: '231873137659',
    projectId: 'onlytransfer-lab',
    authDomain: 'onlytransfer-lab.firebaseapp.com',
    storageBucket: 'onlytransfer-lab.firebasestorage.app',
    measurementId: 'G-1YDG12416E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrZFwH6OmLwNd0DsRTOdDjI1pNVLMB7-M',
    appId: '1:231873137659:android:bc7ecb9cf7e7c46b3d195e',
    messagingSenderId: '231873137659',
    projectId: 'onlytransfer-lab',
    storageBucket: 'onlytransfer-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkEyYOOZEFko2xM4VinSbfSnODpr0LgcE',
    appId: '1:231873137659:ios:a10a0f1600d6cc993d195e',
    messagingSenderId: '231873137659',
    projectId: 'onlytransfer-lab',
    storageBucket: 'onlytransfer-lab.firebasestorage.app',
    iosBundleId: 'com.example.onlyTransfer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkEyYOOZEFko2xM4VinSbfSnODpr0LgcE',
    appId: '1:231873137659:ios:a10a0f1600d6cc993d195e',
    messagingSenderId: '231873137659',
    projectId: 'onlytransfer-lab',
    storageBucket: 'onlytransfer-lab.firebasestorage.app',
    iosBundleId: 'com.example.onlyTransfer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABhzG_yvIzP9y7XaHg3sH1CkTA3JUaXhU',
    appId: '1:231873137659:web:3c3464d9da9129353d195e',
    messagingSenderId: '231873137659',
    projectId: 'onlytransfer-lab',
    authDomain: 'onlytransfer-lab.firebaseapp.com',
    storageBucket: 'onlytransfer-lab.firebasestorage.app',
    measurementId: 'G-5V9CB2SLF7',
  );
}
